version: '2'

volumes:
  nextcloud:
  db:
  zerotier-one:

services:
  zt:
    build: ./zt/
    restart: always
    depends_on: 
      - app
    devices: 
      - /dev/net/tun
    volumes:
      - zerotier-one:/var/lib/zerotier-one
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add: 
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: host

  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: ./nextcloud
    restart: always
    ports:
      - 8080:80
      - 4433:443
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=Tejas
      - NEXTCLOUD_ADMIN_PASSWORD=password
